#!/usr/bin/env python3
# Emits fir_taps.h with __constant__ tap arrays for the bands the pipeline cares about.
# Re-run only when fs or band edges change.

from __future__ import annotations
import sys
from pathlib import Path
import numpy as np
from scipy.signal import firwin

FS = 250.0

# (name, low_hz, high_hz, ntaps). Sub-Hz cutoffs need long filters; >10Hz cutoffs do not.
BANDS = [
    ("BROADBAND", 0.5, 100.0, 257),
    ("DELTA",     0.5,   4.0, 257),
    ("THETA",     4.0,   8.0, 129),
    ("ALPHA",     8.0,  13.0, 129),
    ("BETA",     13.0,  30.0, 129),
    ("GAMMA",    30.0, 100.0, 129),
    ("SSVEP",     5.0,  20.0, 129),
]


def design(low: float, high: float, ntaps: int) -> np.ndarray:
    nyq = FS / 2.0
    high = min(high, nyq - 1.0)  # firwin rejects cutoffs at Nyquist
    return firwin(ntaps, [low, high], pass_zero=False, fs=FS, window="hamming").astype(np.float32)


def emit(out: Path) -> None:
    lines: list[str] = []
    lines.append("// Generated by taps/generate_taps.py — do not edit by hand.")
    lines.append("// fs = %.1f Hz" % FS)
    lines.append("#pragma once")
    lines.append("")
    lines.append("namespace eeg {")
    lines.append("")
    for name, lo, hi, n in BANDS:
        lines.append(f"constexpr int  NTAPS_{name} = {n};")
    lines.append("")
    for name, lo, hi, n in BANDS:
        taps = design(lo, hi, n)
        body = ", ".join(f"{v:.9e}f" for v in taps)
        lines.append(f"// {name}: {lo} – {hi} Hz")
        lines.append(f"__constant__ float TAPS_{name}[{n}] = {{ {body} }};")
        lines.append("")
    lines.append("} // namespace eeg")
    lines.append("")
    out.write_text("\n".join(lines))


if __name__ == "__main__":
    here = Path(__file__).parent
    out = here / "fir_taps.h"
    emit(out)
    print(f"wrote {out} ({out.stat().st_size} bytes)")
