#include <cuda_runtime.h>
#include "kernels.h"

// Default 60 Hz (Americas/Asia). Define NOTCH_FREQ_HZ=50 in your build for European mains.
#ifndef NOTCH_FREQ_HZ
#define NOTCH_FREQ_HZ 60
#endif

namespace eeg {

// Biquad coefficients for fs=250 Hz, Q=30. Generated by taps/generate_taps.py-equivalent math
// (see comment in kernels/notch.cu — values pre-baked to avoid runtime trig).
#if NOTCH_FREQ_HZ == 60
__constant__ float NOTCH_B0 = 0.9836383768f;
__constant__ float NOTCH_B1 = -0.1235263294f;
__constant__ float NOTCH_B2 = 0.9836383768f;
__constant__ float NOTCH_A1 = -0.1235263294f;
__constant__ float NOTCH_A2 = 0.9672767536f;
#elif NOTCH_FREQ_HZ == 50
__constant__ float NOTCH_B0 = 0.9843963900f;
__constant__ float NOTCH_B1 = -0.6083904274f;
__constant__ float NOTCH_B2 = 0.9843963900f;
__constant__ float NOTCH_A1 = -0.6083904274f;
__constant__ float NOTCH_A2 = 0.9687927800f;
#else
#error "NOTCH_FREQ_HZ must be 50 or 60"
#endif

// IIR is sequential per-channel (each output depends on previous outputs/inputs).
// 8 channels at 256 samples is small — under-saturating the GPU is fine, the kernel
// runs in microseconds and isn't the bottleneck.
//
// DF2T: numerically better than DF1 for fixed-Q biquads; only two state words per channel.
__global__ void notch_kernel(float* x, float* z1, float* z2, int n_ch, int n_samp)
{
    int ch = blockIdx.x * blockDim.x + threadIdx.x;
    if (ch >= n_ch) return;
    float s1 = z1[ch];
    float s2 = z2[ch];

    float* xc = x + ch * n_samp;
    for (int n = 0; n < n_samp; ++n) {
        float xn = xc[n];
        float yn = NOTCH_B0 * xn + s1;
        s1 = NOTCH_B1 * xn - NOTCH_A1 * yn + s2;
        s2 = NOTCH_B2 * xn - NOTCH_A2 * yn;
        xc[n] = yn;
    }

    z1[ch] = s1;
    z2[ch] = s2;
}

void launch_notch(float* x, float* z1, float* z2, int n_ch, int n_samp, cudaStream_t s)
{
    int tpb = (n_ch < 32) ? n_ch : 32;
    int blocks = (n_ch + tpb - 1) / tpb;
    notch_kernel<<<blocks, tpb, 0, s>>>(x, z1, z2, n_ch, n_samp);
}

} // namespace eeg
